export default [
  { label: "Aurora Public Library", value: "aurora" },
  { label: "Barrie Public Library", value: "barrie" },
  { label: "Brantford Public Library", value: "brantford" },
  { label: "Burlington Public Library", value: "burlington" },
  { label: "Burnaby Public Library", value: "burnaby" },
  { label: "Calgary Public Library", value: "calgary" },
  { label: "Chinook Arch Regional Library System", value: "chinookarch" },
  { label: "Edmonton Public Library", value: "epl" },
  { label: "Fort Saskatchewan Public Library", value: "fspl" },
  { label: "Fort St John Public Library", value: "fsjpl" },
  { label: "Fraser Valley Regional Library", value: "fvrl" },
  { label: "Greater Sudbury Public Library", value: "gspl" },
  { label: "Halifax Public Libraries", value: "halifax" },
  { label: "Hamilton Public Library", value: "hpl" },
  { label: "Innisfil ideaLAB & Library", value: "innisfil" },
  { label: "Markham Public Library", value: "markham" },
  { label: "Nelson Public Library", value: "nelson" },
  { label: "New Westminster Public Library", value: "newwestminster" },
  { label: "North Perth Public Library", value: "nppl" },
  { label: "Oakville Public Library", value: "opl" },
  { label: "Okanagan Regional Library", value: "orl" },
  { label: "Ottawa Public Library", value: "ottawa" },
  { label: "Oshawa Public Libraries", value: "oshlib" },
];
