export default [
  ["Aurora Public Library", "aurora"],
  ["Barrie Public Library", "barrie"],
  ["Brantford Public Library", "brantford"],
  ["Burlington Public Library", "burlington"],
  ["Burnaby Public Library", "burnaby"],
  ["Calgary Public Library", "calgary"],
  ["Chinook Arch Regional Library System", "chinookarch"],
  ["Edmonton Public Library", "epl"],
  ["Fort Saskatchewan Public Library", "fspl"],
  ["Fort St John Public Library", "fsjpl"],
  ["Fraser Valley Regional Library", "fvrl"],
  ["Greater Sudbury Public Library", "gspl"],
  ["Halifax Public Libraries", "halifax"],
  ["Hamilton Public Library", "hpl"],
  ["Innisfil ideaLAB & Library", "innisfil"],
  ["Markham Public Library", "markham"],
  ["Nelson Public Library", "nelson"],
  ["New Westminster Public Library", "newwestminster"],
  ["North Perth Public Library", "nppl"],
  ["Oakville Public Library", "opl"],
  ["Okanagan Regional Library", "orl"],
  ["Ottawa Public Library", "ottawa"],
  ["Oshawa Public Libraries", "oshlib"],
];
